var a ={
    "_id": ObjectId("59cf0b9bd0b4997842668989"),
    "user": ObjectId("59cf0b9bd0b4997842668988"),
    "classification": {
        "applyDetailType": {
            "IS_EXCEPTIONEE": false,
            "IS_NATIONAL_MERIT": false,
            "IS_COMMON": true
        },
        "applyBaseType": {
            "cause": null,
            "type": "COMMON"
        },
        "graduateYear": "2018",
        "graduateType": "WILL",
        "regionType": "HOME",
        "isBlack": false
    },
    "info": {
        "addressDetail": "503동 802호",
        "addressBase": "경기도 파주시 가온로 67 (목동동, 해솔마을 5단지 삼부르네상스 아파트)",
        "birthday": "2000-04-29",
        "parentsName": "안영숙",
        "parentsTel": "010-2896-2001",
        "tel": "010-2896-2001",
        "schoolTel": "031-941-8832",
        "schoolName": "대덕중학교",
        "schoolCode": "7450010",
        "class": "1",
        "number": "28",
        "grade": 3,
        "sex": "남"
    },
    "grade": {
        "calculatedScore": {
            "total": 18,
            "attendance": 15,
            "volunteer": 3,
            "score": {
                "total": 100,
                "third": 0,
                "second": 0,
                "first": 0
            }
        },
        "score": {
            "semesters": [
                [{
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    }
                ],
                [{
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    }
                ],
                [{
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    }
                ],
                [{
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    }
                ],
                [{
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    },
                    {
                        "grade": null,
                        "pass": false
                    }
                ]
            ]
        },
        "attend": {
            "subjectEscape": 0,
            "earlyLeave": 0,
            "lateness": 0,
            "absence": 0
        },
        "volunteer": "10"
    },
    "introduce": {
        "plan": "안녕하세요",
        "introduce": "안녕하세요"
    },
    "createdAt": "2017-9-30 12:12:27",
    "updatedAt": "2017-9-30 14:8:49",
    "profile": "06857176-c94.jpeg",
    "applyStatus": false,
    "examNumber": null,
    "submitNumber": 2,
    "__v": 0
}