const initialState = {
    name: "",
    email: "",
    password: "",
    privacy: false,
    graduateYear: "",
    graduateType: "",
    local: "",
    applyType: "",
    parentName: "",
    birth: "",
    sex: "",
    postNumber: "",
    address: "",
    class: "",
    phoneNumber: "",
    parentPhoneNumber: "",
    schoolName: "",
    image: "",
    schoolCode: "",
    attend: "",
    volunteerTime: "",
    selfIntroduce: "",
    studyPlan: "",
    
}